#!/bin/bash

DEFAULT_ACCOUNTS_COUNT=3
CHECKED_ACCOUNTS_COUNT=${WAVES_ACCOUNTS_COUNT:-$DEFAULT_ACCOUNTS_COUNT}

DEFAULT_NETWORK_BYTE='C'
CHECKED_NETWORK_BYTE=${WAVES_NETWORK_BYTE:-$DEFAULT_NETWORK_BYTE}

DEFAULT_AVERAGE_BLOCK_DELAY='15'
CHECKED_AVERAGE_BLOCK_DELAY=${WAVES_AVERAGE_BLOCK_DELAY:-$DEFAULT_AVERAGE_BLOCK_DELAY}

DEFAULT_ACCOUNT_SEED=''
CHECKED_WAVES_ACCOUNT_0=${WAVES_ACCOUNT_0:-$DEFAULT_ACCOUNT_SEED}
CHECKED_WAVES_ACCOUNT_1=${WAVES_ACCOUNT_1:-$DEFAULT_ACCOUNT_SEED}
CHECKED_WAVES_ACCOUNT_2=${WAVES_ACCOUNT_2:-$DEFAULT_ACCOUNT_SEED}
CHECKED_WAVES_ACCOUNT_3=${WAVES_ACCOUNT_3:-$DEFAULT_ACCOUNT_SEED}
CHECKED_WAVES_ACCOUNT_4=${WAVES_ACCOUNT_4:-$DEFAULT_ACCOUNT_SEED}

PWD=${OUTPUT:-`pwd`}

WAVES_HOST_OUTPUT_PATH="$PWD/genesis"

echo "Starting wavesplatform/genesis"

docker run -e WAVES_ACCOUNTS_COUNT="$CHECKED_ACCOUNTS_COUNT" -e WAVES_NETWORK_BYTE="$CHECKED_NETWORK_BYTE" -e WAVES_AVERAGE_BLOCK_DELAY="$CHECKED_AVERAGE_BLOCK_DELAY" -e WAVES_HOST_OUTPUT_PATH="$WAVES_HOST_OUTPUT_PATH" -e WAVES_ACCOUNT_0="$CHECKED_WAVES_ACCOUNT_0" -e WAVES_ACCOUNT_1="$CHECKED_WAVES_ACCOUNT_1" -e WAVES_ACCOUNT_2="$CHECKED_WAVES_ACCOUNT_2" -e WAVES_ACCOUNT_3="$CHECKED_WAVES_ACCOUNT_3" -e WAVES_ACCOUNT_4="$CHECKED_WAVES_ACCOUNT_4" -v "$WAVES_HOST_OUTPUT_PATH":/waves-mnt wavesplatform/genesis

cat "$PWD/genesis/output/docker-compose.yml"


echo "Running nodes..."
cd ./genesis/output/
docker-compose up